[phases.setup]
nixPkgs = ["flutter", "nginx"]

[phases.install]
cmds = [
  "flutter --disable-telemetry",
  "flutter pub get"
]

[phases.build]
cmds = ["flutter build web --release"]

[phases.start]
cmds = ["nginx -g 'daemon off;'"]