[phases.setup]
nixPkgs = ["flutter", "curl", "wget"]

[phases.install]
cmds = [
  "flutter upgrade",
  "flutter --disable-telemetry",
  "flutter pub get"
]

[phases.build]
cmds = ["flutter build web --release"]

[start]
cmds = ["echo 'Hello, World!'"]
